### ISSUE TITLE
Error to get Steam wish list

### ISSUE THREAD

**Issue by Lacro59** [Lacro59/playnite-isthereanydeal-plugin#17]
From RabidLime on forum (https://playnite.link/forum/thread-323-post-2701.html#pid2701)

still cannot get this to work for the life of me. have Game Details set to Public, also have an API for a private account. it worked before and now it doesn't. only get the notification attached. incredibly frustrating.

![image](https://user-images.githubusercontent.com/124054/100739006-c40aeb80-33d6-11eb-99ef-231a1d719daf.png)

**Comment by MrNuggelz** [comment]
If it helps, I found a error in the logfile regarding this issue:

```
06-12 12:17:24.935|ERROR|Common:IsThereAnyDeal [??? 78] - Error in parse Steam wishlist

System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JObject'.
   at IsThereAnyDeal.Services.SteamWishlist.GetWishlist(IPlayniteAPI PlayniteApi, Guid SourceId, String PluginUserDataPath, IsThereAnyDealSettings settings, Boolean CacheOnly) in E:\Github\Lacro59\playnite-isthereanydeal-plugin\Clients\SteamWishlist.cs:line 78
```
I looked at this line but see nothing relevant. But I hope this helps you
