### ISSUE TITLE
Fullscreen mode crashes

### ISSUE THREAD

**Issue by MultiversalTraveler** [Lacro59/playnite-isthereanydeal-plugin#22]
Fullscreen mode crashes with "unrecoverable error" when any game price notification in the list is clicked on.  Also, full list is not visible and cannot be scrolled.  Thanks.

**Comment by Lacro59** [comment]
Can you try with the last release?

**Comment by MultiversalTraveler** [comment]
It works fine in desktop mode, but says "failed to load properly" in full screen.
