### ISSUE TITLE
Steam wishlist isn't being imported even with profile as "public"

### ISSUE THREAD

**Issue by ferrazpedro** [Lacro59/playnite-isthereanydeal-plugin#23]
Hey!

I'm having some problems with the Steam wishlist. All the other stores load alright, but Steam doesn't in any way. Is there any other step to do about it after setting the profile to public?

This is how my steam settings are:
![](https://cdn.discordapp.com/attachments/808419165311467630/885246822350745630/unknown.png)

These are the options selected in the extension:
![](https://cdn.discordapp.com/attachments/808419165311467630/885244940467183666/unknown.png)

**Comment by Lacro59** [comment]
Can you try with the last release?

**Comment by ferrazpedro** [comment]
Sorry for taking so long to answer! Now it`s working as expected, thanks a lot @Lacro59!
