### ISSUE TITLE
Extension doesn't check notifications on Playnite Startup

### ISSUE THREAD

**Issue by BradBardoon** [Lacro59/playnite-isthereanydeal-plugin#29]
I have notifications enabled and parameters set, and they do work when I click on extensions>IsThereAnyDeal>Check Notifications, but the extension doesn't seem to check automatically or notify me when Playnite starts. The only way to get notified right now is if I check manually and then it shows new deals with those parameters.

Here is the extensions log. I was testing to make sure, so it shows that I did a manual check pretty often.
[extensions.log](https://github.com/Lacro59/playnite-isthereanydeal-plugin/files/7449304/extensions.log)

I don't know if this could be related, but it also doesn't update my wishlist automatically on startup, only when I click "Update IsThereAnyDeal Data" in the extensions menu, only then are the games I added to my Steam wishlist are added to the extension. Though perhaps that's how it's supposed to work.

This likely also isn't related, but when I go to the Add-on menu and configure the extension, it doesn't show the Notification settings text. I can still click it, so I can still set the parameters, but the text at the top is just missing and the parameters are displayed with the actual code.
![image](https://user-images.githubusercontent.com/84147288/139594625-44fac65f-265d-4866-8e0d-602d4cac4e39.png)

I'm on Windows 10, using Playnite 9 with everything up to date, and the Harmony theme. Let me know if I need to provide any additional information.

**Comment by OsoaGH** [comment]
same here

**Comment by woutercools** [comment]
+1

**Comment by OsoaGH** [comment]
hey @Lacro59 didn't want to ping but considering how useful this plugin is, can you please try to fix it or at least let us know you're fixing it?

**Comment by OsoaGH** [comment]
thanks!

**Comment by woutercools** [comment]
yes! Thank you.

**Comment by BradBardoon** [comment]
Awesome~!
