### ISSUE TITLE
The extension don`t give the option to chose countries other than us

### ISSUE THREAD

**Issue by ferrazpedro** [Lacro59/playnite-isthereanydeal-plugin#34]
Hey! I`ve been having this problem for a while. Since the P9 update of the extension, it doesn`t show options other than US for the country, and some select currencies.

![image](https://user-images.githubusercontent.com/37643357/144612082-38a4d294-c9f3-4000-b14b-660b5e44a413.png)

![image](https://user-images.githubusercontent.com/37643357/144612096-d7a1f236-cf12-48f2-ba98-4498a91f5223.png)

Before, it game me the option to chose my own country and currency like it`s in ITAD. Is this new behavior the expected?

**Comment by Lacro59** [comment]
The list of countries is got from ITAD api.

**Comment by ATNewHope** [comment]
> 
I see. However, US is not my actual region. 
Since the extension doesn't require an ITAD accout to obtain configured region, how could I let the API know the correct region?

**Comment by Lacro59** [comment]
You must select the good region in plugin settings.
Next, you can select the good countries.
By default, the region is `US` in plugin.

**Comment by ATNewHope** [comment]
> You must select the good region in plugin settings. Next, you can select the good countries. By default, the region is `US` in plugin.

Thanks, I see. But I can't find CN(China), which is however supported on ITAD.

**Comment by ferrazpedro** [comment]
I'm in the same situation as @ATNewHope . The extensions only shows US as the country and doesn't show my region, even though it's supported by ITAD.
