### ISSUE TITLE
Extension "IsThereAnyDeal" failed to load properly

### ISSUE THREAD

**Issue by lukaszrzasik** [Lacro59/playnite-isthereanydeal-plugin#43]
Hello, I have recently noticed that the extension fails to load.

Please find below the relevant logs. There are no extension logs. There is some polish words in the logs. I don't know how to change the language. Probably in depends on Windows' language. If you need the translation of the specific sentence I can provide one done by me. Thanks!

> 24-09 15:23:15.159|ERROR|ExtensionFactory:Failed to load plugin: IsThereAnyDeal
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.Reflection.ReflectionTypeLoadException: Nie można załadować jednego lub większej liczby żądanych typów. Aby uzyskać więcej informacji, pobierz właściwość LoaderExceptions.
>    w System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
>    w System.Reflection.RuntimeModule.GetTypes()
>    w System.Reflection.Assembly.GetTypes()
>    w Playnite.Plugins.ExtensionFactory.<LoadPlugins>d__33.MoveNext() w C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:wiersz 449
>    w Playnite.Plugins.ExtensionFactory.LoadPlugins(List`1 ignoreList, Boolean builtInOnly, List`1 externals) w C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:wiersz 409
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.174|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.190|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.190|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.190|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.190|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.
> 24-09 15:23:15.190|ERROR|ExtensionFactory:
> System.TypeLoadException: Metoda 'BufferedUpdate' w typie 'CommonPlayniteShared.Database.ItemCollection`1' z zestawu 'IsThereAnyDeal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' nie ma implementacji.

**Comment by Lacro59** [comment]
fixed with the last release
