### ISSUE TITLE
Error message after every data update

### ISSUE THREAD

**Issue by lofidevops** [Lacro59/playnite-isthereanydeal-plugin#54]
After every data update I get one of two error messages:

> Object reference not set to an instance of an object.

or

> Unexpected character encountered while parsing value: <. Path “, line 0, position 0.

How can I provide more information?

**Comment by Andei** [comment]
Same here

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-isthereanydeal-plugin/commit/a592cf88d445884366d182c56e5ac5ccf4cf60a1
