### ISSUE TITLE
No Plugin Settings Available

### ISSUE THREAD

**Issue by tomblind** [Lacro59/playnite-isthereanydeal-plugin#8]
After installing the plugin, no settings appear in Playnite.

This looks like a great plugin - hope I can get it working!

![pnitadbug](https://user-images.githubusercontent.com/26638278/90909764-7fad8f80-e393-11ea-88b1-d844dbe1bbdb.png)

**Comment by PassiveLemon** [comment]
Sorry to bump but I also have this issue right now. I don't see settings for IsThereAnyDeal or DuplicateHider
